version: '3'
services:
    blocks_Container:
      build: /home/deq/Desktop/Projects/python_Docker/Docker_Container_1/
      image: "dockercompose/blocks:1.0"
      container_name: "blocks_container1"
      ports: 
        - 9229:9229

    contracts_Container:
      build: /home/deq/Desktop/Projects/python_Docker/Docker_Container_2/
      image: "dockercompose/contracts:2.0"
      container_name: "contracts_container2"
      ports:
        - 8000:8000
      

    holders_Container:
      build: /home/deq/Desktop/Projects/python_Docker/Docker_Container_3/
      image: "dockercompose/holders:3.0"
      container_name: "contracts_container3"
      ports:
        - 5678:5678

      
